### ISSUE TITLE
Refactorize into controller?

### ISSUE THREAD

**Issue by dfridovi** [jsalfity/sensitivity_games#2]
https://github.com/jsalfity/sensitivity_games/blob/5e5bb376f0d221e2df371b6b248d67b2990336ad/src/trajectory.py#L41

It looks like the controller is built into the dynamics right now. I'm not sure that's a great idea - I imagine we'll want to see how different controllers perform on the same system. I suggest factoring this functionality into a separate abstract `Controller` class. For example, you could have a derived class `LinearFeedbackController(Controller)` or the full on `NeuralNetworkController(Controller)`.

**Comment by jsalfity** [comment]
created a `controller.py` class with the two controllers you mentioned. kept them all in one file, a bit easier for me to read
