### ISSUE TITLE
State and control costs?

### ISSUE THREAD

**Issue by dfridovi** [jsalfity/sensitivity_games#3]
https://github.com/jsalfity/sensitivity_games/blob/5e5bb376f0d221e2df371b6b248d67b2990336ad/src/trajectory.py#L14

Not sure what these are doing here? I suggest factoring out all cost-related operations into a separate class which has a function that takes `Trajectory` and just evaluates all the costs and adds them up.

**Comment by dfridovi** [comment]
Ah I see now - reading the `unroll()` function. It seems like you're integrating the trajectory forward by applying a linear feedback control (which I think might be simpler if it's factored out per #2) then computing the total cost directly without actually saving the trajectory. I think it'll just save us a headache and make debugging easier to be save the trajectory and then, separately afterward, map it to the cost. That way we can do things like plot the trajectories directly.

**Comment by jsalfity** [comment]
extracted the controller from trajectory.
