### ISSUE TITLE
motion in the game

### ISSUE THREAD

**Issue by jsalfity** [jsalfity/sensitivity_games#4]
Do we want to add another variable in the dynamics, say motion perturbations or a reference trajectory to track, so the controller is following and/or disturbance rejection ? Do we need to have x and y velocities non zero?

i.e I'm not sure what to draw from K and theta iterating to convergence when x,y position nominal values are set to zero. Intuitively, it seems like there is no motion / external input to achieve, so K would end up being all zeros.  

https://github.com/jsalfity/sensitivity_games/blob/68192f00bb490540a4778e0ef8069b07c5d30485/src/main.py#L27-L31

**Comment by dfridovi** [comment]
Oh so this is just a "regulate to the origin" classic LQR problem. `K` will not be all zeros - it will basically try to modify the poles of `A - BK` so that the closed loop dynamics converge to the origin quickly, despite `\theta` doing whatever it's doing.

**Comment by jsalfity** [comment]
Ah, hmm, I think I missed the initial conditions, is this right ... 

With `x0 = Tensor([1, 0, 1, 0])` and `traj_cost.addStateCost(Quadratic(n=0, d=0))  # x position` and  `traj_cost.addStateCost(Quadratic(n=0,d=2))  # y position`, we'll start the trajectory at `x=1`, `y=1` and calculate quadratic cost from the nominal of `x=0`, `y=0`, where the `optimizer_K` will try to find the best `K` to move from `(1,1)` to `(0,0)` while `optimizer_theta` will try to find the worst theta to move from `(1,1)` to `(0,0)`.

**Comment by dfridovi** [comment]
Yeah that's what I think we're trying for ;)

**Comment by jsalfity** [comment]
added a visualize with point mass
