### ISSUE TITLE
get_control

### ISSUE THREAD

**Issue by jsalfity** [jsalfity/sensitivity_games#5]
This cannot be correct. K should be acting on error, i.e. `x_current - x_final`, rather than just acting on the state. Caught the error when visualizing converged K and dare K with xf/goal state other than [0 0 0 0]. 

```py
    def get_control(self, x):
        '''
        '''
        return -self.K @ x
```

proposed fix:
```py
    def get_control(self, x, xf):
        '''
        '''
        return -self.K @ (x-xf)
```

And need to add
```py
            self.U.append(controller.get_control(self.X[-1], self.xf))
```
in https://github.com/jsalfity/sensitivity_games/blob/main/sensitivity_games/trajectory.py#L25.

@dfridovi -- Question is how to elegantly introduce xf into the abstraction architecture? Is that how you would do it?

https://github.com/jsalfity/sensitivity_games/blob/cfa75bf6eb892ef098bb81e08ec1e981753d2018/sensitivity_games/linear_feedback_controller.py#L39-L42

**Comment by dfridovi** [comment]
Very good catch. And yes, this would definitely work, although I tend to think that the better abstraction would be to keep the existing function signature and factor the reference state in as a member variable. The logic here is that we probably don't want to restrict ourselves to reference tracking if we're targeting something like a mujoco task.

**Comment by dfridovi** [comment]
Also, I suggest in future creating a parallel pull request for issues like this and only merging it when it's ready. That way, `main` is always clean in case you want to work on multiple self-contained features in parallel. You can totally still reference the issue and PR as usual.

**Comment by jsalfity** [comment]
okay, just reverted the commit. So I'll write a proposed solution on a new branch, then pull into master?

**Comment by dfridovi** [comment]
Yeah I think the workflow I've seen is something like:
1. identify problem and discuss general solution strategy in issue
2. open WIP PR referencing issue
3. work on PR and discuss specific implementation decisions in the comments there
4. if it makes sense, add unit test(s) which require new fixes to pass
5. merge

**Comment by jsalfity** [comment]
for the sake of practice, i just opened up a `controller_fix` branch.

Two options seem feasible, but need help on which is preferred  -- 
1 .`xf` is member in `Dynamics` class, https://github.com/jsalfity/sensitivity_games/blob/controller_fix/sensitivity_games/dynamics.py
2. `xf` is member in `Controller` class, https://github.com/jsalfity/sensitivity_games/blob/controller_fix/sensitivity_games/controller.py

Another fix could be in the `Trajectory.unroll` function, but I think that's correct.
https://github.com/jsalfity/sensitivity_games/blob/controller_fix/sensitivity_games/trajectory.py#L15-L30

**Comment by dfridovi** [comment]
I'd make `xf` a member of the `Controller` class, but actually I'd probably first subclass `Controller` to something like `Regulator` or `TrackingController` and then put `LinearFeedbackController` as a subclass of that. That way `xf` wouldn't be a property of all `Controller`s but only those that track a reference. The only issue here is that it's common to have a time-varying reference, but tbh my feeling is that most of these fixes would be totally fine and any issues that came up we could fix then.
